alter table if exists public.hyperlinks add column if not exists connection_type text;
alter table if exists public.hyperlinks add column if not exists chapter_reference text;
alter table if exists public.hyperlinks add column if not exists strength numeric;
alter table if exists public.hyperlinks alter column active set default true;
alter table if exists public.hyperlinks alter column metadata set default '{}'::jsonb;
alter table if exists public.dualism_relations add column if not exists paragraph_id uuid;
alter table if exists public.dualism_relations add column if not exists node_a text;
alter table if exists public.dualism_relations add column if not exists node_b text;
alter table if exists public.dualism_relations add column if not exists theme_node_a text;
alter table if exists public.dualism_relations add column if not exists theme_node_b text;
alter table if exists public.dualism_relations add column if not exists axis text;
alter table if exists public.dualism_relations add column if not exists polarity text;
alter table if exists public.dualism_relations add column if not exists evidence text;
alter table if exists public.dualism_relations add column if not exists analysis text;
alter table if exists public.dualism_relations add column if not exists semantic_hash text;
alter table if exists public.dualism_relations alter column active set default true;
alter table if exists public.dualism_relations alter column metadata set default '{}'::jsonb;
alter table if exists public.dualism_relation_evidence add column if not exists semantic_run_id uuid;
alter table if exists public.dualism_relation_evidence add column if not exists relation_id uuid;
alter table if exists public.dualism_relation_evidence add column if not exists evidence text;
alter table if exists public.dualism_relation_evidence add column if not exists quote text;
alter table if exists public.dualism_relation_evidence add column if not exists chapter_reference text;
alter table if exists public.dualism_relation_evidence add column if not exists confidence numeric default 0;
alter table if exists public.dualism_relation_evidence add column if not exists semantic_hash text;
alter table if exists public.dualism_relation_evidence add column if not exists active boolean default true;
alter table if exists public.dualism_relation_evidence alter column metadata set default '{}'::jsonb;
alter table if exists public.archetype_observations add column if not exists character_name text;
alter table if exists public.archetype_observations add column if not exists character text;
alter table if exists public.archetype_observations add column if not exists phase text;
alter table if exists public.archetype_observations add column if not exists evidence text;
alter table if exists public.archetype_observations add column if not exists analysis text;
alter table if exists public.archetype_observations alter column active set default true;
alter table if exists public.archetype_observations alter column metadata set default '{}'::jsonb;
alter table if exists public.archetype_movements add column if not exists paragraph_id uuid;
alter table if exists public.archetype_movements add column if not exists archetype_observation_id uuid;
alter table if exists public.archetype_movements add column if not exists character_name text;
alter table if exists public.archetype_movements add column if not exists character text;
alter table if exists public.archetype_movements add column if not exists archetype text;
alter table if exists public.archetype_movements add column if not exists from_phase text;
alter table if exists public.archetype_movements add column if not exists to_phase text;
alter table if exists public.archetype_movements add column if not exists movement_type text;
alter table if exists public.archetype_movements add column if not exists evidence_text text;
alter table if exists public.archetype_movements add column if not exists evidence text;
alter table if exists public.archetype_movements add column if not exists analysis text;
alter table if exists public.archetype_movements alter column active set default true;
alter table if exists public.archetype_movements alter column metadata set default '{}'::jsonb;
alter table if exists public.biblical_references add column if not exists reference text;
alter table if exists public.biblical_references add column if not exists motif text;
alter table if exists public.biblical_references add column if not exists evidence text;
alter table if exists public.biblical_references add column if not exists analysis text;
alter table if exists public.biblical_references alter column active set default true;
alter table if exists public.biblical_references alter column metadata set default '{}'::jsonb;
